#!/bin/bash
REDIS_SERVER="/usr/local/redis/bin/redis-server"
REDIS_CONF="/usr/local/redis/conf/redis.conf"
REDIS_PORT=6379
PID_FILE="/usr/local/redis/data/redis.pid"

case $1 in
status)
    if [ -e "${PID_FILE}" ];then
        echo "Redis is Running..."
    else
        echo "Redis is not Running..."
    fi
    ;;
start)
    if [ -e "${PID_FILE}" ];then
        echo "Redis is Running..."
        exit 11
    fi
    ${REDIS_SERVER} ${REDIS_CONF} &> /dev/null
    sleep 2
    if [ -e "${PID_FILE}" ];then
        echo "Redis Starting..."
    else
        echo "Redis Start Failed, Please Check in Manual..."
    fi
    ;;
stop)
    if [ -e "${PID_FILE}" ];then
        pkill redis-server
    else
        echo "Redis is not Running..."
    fi
    ;;
restart)
    if [ -e "${PID_FILE}" ];then
        pkill redis-server
    fi
    ${REDIS_SERVER} ${REDIS_CONF}
    ;;
*)
    echo "Usage $0 {status|start|stop|restart}"
esac
